### PR TITLE
Demo

### PR DESCRIPTION
**Pull request by ducminhle**

### CODE REVIEW

**Comment by cin-otis** [comment]
Ran Plan for project: `demo` dir: `demo` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.demo will be created
+ resource "null_resource" "demo" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p demo`
* :put_litter_in_its_place: To **delete** this plan click [here](http://18.178.60.96:4141/lock?id=Cinnamon%252Fatlantis-example%252Fdemo%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p demo`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by ducminhle** [comment]
atlantis apply -p demo

**Comment by cin-otis** [comment]
Ran Apply for project: `demo` dir: `demo` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by cin-otis — APPROVED** [review]

**Comment by ducminhle** [comment]
atlantis apply -p demo

**Comment by cin-otis** [comment]
Ran Apply for project: `demo` dir: `demo` workspace: `default`

```diff
null_resource.demo: Creating...
null_resource.demo: Creation complete after 0s [id=1364333125451916377]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


```

**Comment by cin-otis** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by cin-otis** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `demo` workspace: `default`

**Pull request merged**
